
CREATE DATABASE IF NOT EXISTS wk8_challenge DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE wk8_challenge;


CREATE TABLE IF NOT EXISTS notes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
